### ISSUE TITLE
npm install on windows fails

### ISSUE THREAD

**Issue by jadh4v** [floryst/CustomVolViewTemplate#1]
```bash
$ npm install

> customvolviewtemplate@1.0.0 postinstall
> npm run update:core && npm run install:core && npm run sync-config && npx patch-package


> customvolviewtemplate@1.0.0 update:core
> node ./customizeUtils/bin/updateCore.mjs


> customvolviewtemplate@1.0.0 install:core
> node ./customizeUtils/bin/installCore.mjs

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
    at new NodeError (node:internal/errors:405:5)
    at _write (node:internal/streams/writable:302:11)
    at Writable.write (node:internal/streams/writable:337:10)
    at main (file:///D:/code/CustomVolViewTemplate/customizeUtils/bin/installCore.mjs:12:20)
    at file:///D:/code/CustomVolViewTemplate/customizeUtils/bin/installCore.mjs:17:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'ERR_STREAM_NULL_VALUES'
}

Node.js v18.17.1
npm ERR! code 1
npm ERR! path D:\code\CustomVolViewTemplate
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run update:core && npm run install:core && npm run sync-config && npx patch-package

npm ERR! A complete log of this run can be found in: C:\Users\shreeraj.jadhav\AppData\Local\npm-cache\_logs\2023-09-11T16_31_40_946Z-debug-0.log
```

**Comment by jadh4v** [comment]
The `@itk-wasm/dicom` patch is also outdated for v3.3.0. Possibly no longer required.
